import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/glucose_entry.dart';
import '../models/targets.dart';
import 'report_service.dart';

class PdfReportService {
  static Future<void> generateAndShare({
    required ReportData report,
    required List<GlucoseEntry> entries,
    required GlycemicTargets targets,
  }) async {
    final pdf = pw.Document();
    final theme = pw.ThemeData.withFont(
      base: await PdfGoogleFonts.nunitoRegular(),
      bold: await PdfGoogleFonts.nunitoBold(),
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        theme: theme,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text('Glucose Report',
                style: pw.TextStyle(
                    fontSize: 24, fontWeight: pw.FontWeight.bold)),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
              'Period: ${_fmtDate(report.periodStart)} – ${_fmtDate(report.periodEnd)}'),
          pw.Text('Target stratum: ${report.stratumLabel}'),
          pw.Text(
              'Readings: ${report.count} over ${report.daysLogged}/${report.totalDays} days'),
          pw.SizedBox(height: 20),
          _sectionHeader('Glycemic Metrics'),
          _metricRow('Mean glucose',
              report.mean != null ? '${report.mean!.toStringAsFixed(0)} mg/dL' : '—'),
          _metricRow(
              'GMI', report.gmi != null ? '${report.gmi!.toStringAsFixed(1)}%' : '—'),
          _metricRow(
              'CV', report.cv != null ? '${report.cv!.toStringAsFixed(1)}%' : '—'),
          pw.SizedBox(height: 8),
          _tirBar(report),
          pw.SizedBox(height: 20),
          _sectionHeader('Clinical Events'),
          _metricRow('Hypoglycemia (<70)', '${report.hypoEvents} events'),
          _metricRow('Severe hypoglycemia (<54)', '${report.severeHypoEvents} events'),
          _metricRow('Hyperglycemia (>250)', '${report.hyperEvents} events'),
          if (report.fastingCount > 0) ...[
            pw.SizedBox(height: 12),
            _sectionHeader('Fasting Glucose'),
            _metricRow('Fasting readings', '${report.fastingCount}'),
            if (report.fastingMean != null)
              _metricRow('Fasting mean',
                  '${report.fastingMean!.toStringAsFixed(0)} mg/dL'),
          ],
          if (report.medicationAdherence.isNotEmpty) ...[
            pw.SizedBox(height: 12),
            _sectionHeader('Medication Adherence'),
            for (final line in report.medicationAdherence)
              _metricRow('', line),
          ],
          if (report.insights.isNotEmpty) ...[
            pw.SizedBox(height: 12),
            _sectionHeader('Trend Insights'),
            for (final insight in report.insights) ...[
              pw.Text(insight.title,
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 2),
              pw.Text(insight.body),
              pw.SizedBox(height: 8),
            ],
          ],
          pw.SizedBox(height: 12),
          _sectionHeader('Focus'),
          pw.Text(report.focusSuggestion),
          pw.SizedBox(height: 20),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Text(
              'This report is informational and generated from your logged data. '
              'It is not a medical diagnosis. Share with your care team for clinical decisions.',
              style: pw.TextStyle(
                  fontSize: 9, color: PdfColors.grey700),
            ),
          ),
          pw.SizedBox(height: 12),
          pw.Text(
            'Generated by Diabetic Companion',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
          ),
        ],
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'glucose-report.pdf');
  }

  static pw.Widget _sectionHeader(String text) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 8),
        child: pw.Text(text,
            style: pw.TextStyle(
                fontSize: 14, fontWeight: pw.FontWeight.bold)),
      );

  static pw.Widget _metricRow(String label, String value) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 3),
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            if (label.isNotEmpty) pw.Text(label),
            pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          ],
        ),
      );

  static pw.Widget _tirBar(ReportData report) {
    final total = report.tbrPercent + report.tirPercent + report.tarPercent;
    if (total == 0) return pw.SizedBox.shrink();
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(
          height: 20,
          child: pw.Row(
            children: [
              pw.Expanded(
                flex: ((report.tbrPercent / total) * 100).toInt().clamp(1, 100),
                child: pw.Container(color: PdfColors.red300),
              ),
              pw.Expanded(
                flex: ((report.tirPercent / total) * 100).toInt().clamp(1, 100),
                child: pw.Container(color: PdfColors.green700),
              ),
              pw.Expanded(
                flex: ((report.tarPercent / total) * 100).toInt().clamp(1, 100),
                child: pw.Container(color: PdfColors.orange300),
              ),
            ],
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
                'TBR ${report.tbrPercent.toStringAsFixed(1)}%',
                style: pw.TextStyle(
                    fontSize: 9, color: PdfColors.red700)),
            pw.Text(
                'TIR ${report.tirPercent.toStringAsFixed(1)}%',
                style: pw.TextStyle(
                    fontSize: 9, color: PdfColors.green900)),
            pw.Text(
                'TAR ${report.tarPercent.toStringAsFixed(1)}%',
                style: pw.TextStyle(fontSize: 9)),
          ],
        ),
      ],
    );
  }

  static String _fmtDate(DateTime d) =>
      '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';
}
